//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class HighlighterControllerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(HighlighterController), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("MouseOver", MouseOver);
		L.RegFunction("Fire1", Fire1);
		L.RegFunction("Fire2", Fire2);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("seeThrough", get_seeThrough, set_seeThrough);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int MouseOver(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			HighlighterController obj = (HighlighterController)ToLua.CheckObject(L, 1, typeof(HighlighterController));
			obj.MouseOver();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Fire1(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			HighlighterController obj = (HighlighterController)ToLua.CheckObject(L, 1, typeof(HighlighterController));
			obj.Fire1();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Fire2(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			HighlighterController obj = (HighlighterController)ToLua.CheckObject(L, 1, typeof(HighlighterController));
			obj.Fire2();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_seeThrough(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			HighlighterController obj = (HighlighterController)o;
			bool ret = obj.seeThrough;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index seeThrough on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_seeThrough(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			HighlighterController obj = (HighlighterController)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.seeThrough = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index seeThrough on a nil value" : e.Message);
		}
	}
}

