//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaTestMediator4Wrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LuaTestMediator4), typeof(System.Object));
		L.RegFunction("UpdateItems", UpdateItems);
		L.RegFunction("OnInit", OnInit);
		L.RegFunction("GetBagItemData", GetBagItemData);
		L.RegFunction("UseItem", UseItem);
		L.RegFunction("UseAllItems", UseAllItems);
		L.RegFunction("OnDestroy", OnDestroy);
		L.RegFunction("New", _CreateLuaTestMediator4);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateLuaTestMediator4(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				LuaTestMediator4 obj = new LuaTestMediator4();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: LuaTestMediator4.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateItems(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaTestMediator4 obj = (LuaTestMediator4)ToLua.CheckObject(L, 1, typeof(LuaTestMediator4));
			object arg0 = ToLua.ToVarObject(L, 2);
			obj.UpdateItems(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnInit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaTestMediator4 obj = (LuaTestMediator4)ToLua.CheckObject(L, 1, typeof(LuaTestMediator4));
			obj.OnInit();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetBagItemData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaTestMediator4 obj = (LuaTestMediator4)ToLua.CheckObject(L, 1, typeof(LuaTestMediator4));
			LuaInterface.LuaTable o = obj.GetBagItemData();
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UseItem(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaTestMediator4 obj = (LuaTestMediator4)ToLua.CheckObject(L, 1, typeof(LuaTestMediator4));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.UseItem(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UseAllItems(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaTestMediator4 obj = (LuaTestMediator4)ToLua.CheckObject(L, 1, typeof(LuaTestMediator4));
			obj.UseAllItems();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnDestroy(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaTestMediator4 obj = (LuaTestMediator4)ToLua.CheckObject(L, 1, typeof(LuaTestMediator4));
			obj.OnDestroy();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

