//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaTestMediatorWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LuaTestMediator), typeof(System.Object));
		L.RegFunction("UpdateItems", UpdateItems);
		L.RegFunction("OnInit", OnInit);
		L.RegFunction("OnDestroy", OnDestroy);
		L.RegFunction("New", _CreateLuaTestMediator);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("m_LuaTestView", get_m_LuaTestView, set_m_LuaTestView);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateLuaTestMediator(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				LuaTestMediator obj = new LuaTestMediator();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: LuaTestMediator.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateItems(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaTestMediator obj = (LuaTestMediator)ToLua.CheckObject(L, 1, typeof(LuaTestMediator));
			obj.UpdateItems();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnInit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaTestMediator obj = (LuaTestMediator)ToLua.CheckObject(L, 1, typeof(LuaTestMediator));
			obj.OnInit();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnDestroy(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			LuaTestMediator obj = (LuaTestMediator)ToLua.CheckObject(L, 1, typeof(LuaTestMediator));
			obj.OnDestroy();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_LuaTestView(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaTestMediator obj = (LuaTestMediator)o;
			LuaOutlet ret = obj.m_LuaTestView;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index m_LuaTestView on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_LuaTestView(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			LuaTestMediator obj = (LuaTestMediator)o;
			LuaOutlet arg0 = (LuaOutlet)ToLua.CheckUnityObject(L, 2, typeof(LuaOutlet));
			obj.m_LuaTestView = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index m_LuaTestView on a nil value" : e.Message);
		}
	}
}

