//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ProxyManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ProxyManager), typeof(Singleton<ProxyManager>));
		L.RegFunction("Add", Add);
		L.RegFunction("Remove", Remove);
		L.RegFunction("Get", Get);
		L.RegFunction("OnReset", OnReset);
		L.RegFunction("OnInit", OnInit);
		L.RegFunction("New", _CreateProxyManager);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("IsInit", get_IsInit, set_IsInit);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateProxyManager(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				ProxyManager obj = new ProxyManager();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: ProxyManager.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Add(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ProxyManager obj = (ProxyManager)ToLua.CheckObject(L, 1, typeof(ProxyManager));
			IProxy arg0 = (IProxy)ToLua.CheckObject(L, 2, typeof(IProxy));
			obj.Add(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Remove(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ProxyManager obj = (ProxyManager)ToLua.CheckObject(L, 1, typeof(ProxyManager));
			System.Type arg0 = (System.Type)ToLua.CheckObject(L, 2, typeof(System.Type));
			obj.Remove(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Get(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ProxyManager obj = (ProxyManager)ToLua.CheckObject(L, 1, typeof(ProxyManager));
			string arg0 = ToLua.CheckString(L, 2);
			object o = obj.Get(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnReset(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ProxyManager obj = (ProxyManager)ToLua.CheckObject(L, 1, typeof(ProxyManager));
			obj.OnReset();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnInit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ProxyManager obj = (ProxyManager)ToLua.CheckObject(L, 1, typeof(ProxyManager));
			obj.OnInit();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_IsInit(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProxyManager obj = (ProxyManager)o;
			bool ret = obj.IsInit;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index IsInit on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_IsInit(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ProxyManager obj = (ProxyManager)o;
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.IsInit = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index IsInit on a nil value" : e.Message);
		}
	}
}

