//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class WorldMediatorWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(WorldMediator), typeof(System.Object));
		L.RegFunction("OnMoveClick", OnMoveClick);
		L.RegFunction("OnAttackClick", OnAttackClick);
		L.RegFunction("OnGoOutClick", OnGoOutClick);
		L.RegFunction("OnOccupyClick", OnOccupyClick);
		L.RegFunction("OnAssistantClick", OnAssistantClick);
		L.RegFunction("OnInfoClick", OnInfoClick);
		L.RegFunction("OnFocusClick", OnFocusClick);
		L.RegFunction("OnRecallClick", OnRecallClick);
		L.RegFunction("OnEvacuateClick", OnEvacuateClick);
		L.RegFunction("OnTradeClick", OnTradeClick);
		L.RegFunction("OnMarchClick", OnMarchClick);
		L.RegFunction("SetMarchState", SetMarchState);
		L.RegFunction("SetButtons", SetButtons);
		L.RegFunction("OnInit", OnInit);
		L.RegFunction("OnDestroy", OnDestroy);
		L.RegFunction("New", _CreateWorldMediator);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("m_View", get_m_View, set_m_View);
		L.RegVar("m_UIName", get_m_UIName, set_m_UIName);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateWorldMediator(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				WorldMediator obj = new WorldMediator();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: WorldMediator.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnMoveClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WorldMediator obj = (WorldMediator)ToLua.CheckObject(L, 1, typeof(WorldMediator));
			obj.OnMoveClick();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnAttackClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WorldMediator obj = (WorldMediator)ToLua.CheckObject(L, 1, typeof(WorldMediator));
			obj.OnAttackClick();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnGoOutClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WorldMediator obj = (WorldMediator)ToLua.CheckObject(L, 1, typeof(WorldMediator));
			obj.OnGoOutClick();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnOccupyClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WorldMediator obj = (WorldMediator)ToLua.CheckObject(L, 1, typeof(WorldMediator));
			obj.OnOccupyClick();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnAssistantClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WorldMediator obj = (WorldMediator)ToLua.CheckObject(L, 1, typeof(WorldMediator));
			obj.OnAssistantClick();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnInfoClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WorldMediator obj = (WorldMediator)ToLua.CheckObject(L, 1, typeof(WorldMediator));
			obj.OnInfoClick();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnFocusClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WorldMediator obj = (WorldMediator)ToLua.CheckObject(L, 1, typeof(WorldMediator));
			obj.OnFocusClick();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnRecallClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WorldMediator obj = (WorldMediator)ToLua.CheckObject(L, 1, typeof(WorldMediator));
			obj.OnRecallClick();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnEvacuateClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WorldMediator obj = (WorldMediator)ToLua.CheckObject(L, 1, typeof(WorldMediator));
			obj.OnEvacuateClick();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnTradeClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WorldMediator obj = (WorldMediator)ToLua.CheckObject(L, 1, typeof(WorldMediator));
			obj.OnTradeClick();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnMarchClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			WorldMediator obj = (WorldMediator)ToLua.CheckObject(L, 1, typeof(WorldMediator));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.OnMarchClick(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetMarchState(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			WorldMediator obj = (WorldMediator)ToLua.CheckObject(L, 1, typeof(WorldMediator));
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			string arg2 = ToLua.CheckString(L, 4);
			obj.SetMarchState(arg0, arg1, arg2);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetButtons(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WorldMediator obj = (WorldMediator)ToLua.CheckObject(L, 1, typeof(WorldMediator));
			obj.SetButtons();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnInit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WorldMediator obj = (WorldMediator)ToLua.CheckObject(L, 1, typeof(WorldMediator));
			obj.OnInit();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnDestroy(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			WorldMediator obj = (WorldMediator)ToLua.CheckObject(L, 1, typeof(WorldMediator));
			obj.OnDestroy();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_View(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WorldMediator obj = (WorldMediator)o;
			LuaInterface.LuaTable ret = obj.m_View;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index m_View on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_UIName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WorldMediator obj = (WorldMediator)o;
			string ret = obj.m_UIName;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index m_UIName on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_View(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WorldMediator obj = (WorldMediator)o;
			LuaTable arg0 = ToLua.CheckLuaTable(L, 2);
			obj.m_View = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index m_View on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_UIName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			WorldMediator obj = (WorldMediator)o;
			string arg0 = ToLua.CheckString(L, 2);
			obj.m_UIName = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index m_UIName on a nil value" : e.Message);
		}
	}
}

